coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
discovery.uri=http://localhost:8080 # For single-node clusters, this should point to the http-server.http.port of the coordinator